//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AvanteSales.Pro.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AvanteSales.Soap", Namespace="http://tempuri.org/")]
    public partial class AvanteSales : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetServerDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpresasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GravaLogSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsEmpregadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpdateInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCabFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificaVersaoDLLOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaImagemOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargaParcialOperationCompleted;
        
        private System.Threading.SendOrPostCallback DescargaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AvanteSales() {
            this.Url = "http://localhost/AvanteSales/WSSales/AvanteSales.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetServerDateCompletedEventHandler GetServerDateCompleted;
        
        /// <remarks/>
        public event GetEmpresasCompletedEventHandler GetEmpresasCompleted;
        
        /// <remarks/>
        public event GravaLogSyncCompletedEventHandler GravaLogSyncCompleted;
        
        /// <remarks/>
        public event IsEmpregadoCompletedEventHandler IsEmpregadoCompleted;
        
        /// <remarks/>
        public event GetUpdateInfoCompletedEventHandler GetUpdateInfoCompleted;
        
        /// <remarks/>
        public event GetCabFilesCompletedEventHandler GetCabFilesCompleted;
        
        /// <remarks/>
        public event VerificaVersaoDLLCompletedEventHandler VerificaVersaoDLLCompleted;
        
        /// <remarks/>
        public event CargaImagemCompletedEventHandler CargaImagemCompleted;
        
        /// <remarks/>
        public event CargaCompletedEventHandler CargaCompleted;
        
        /// <remarks/>
        public event CargaParcialCompletedEventHandler CargaParcialCompleted;
        
        /// <remarks/>
        public event DescargaCompletedEventHandler DescargaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetServerDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetServerDate() {
            object[] results = this.Invoke("GetServerDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetServerDateAsync() {
            this.GetServerDateAsync(null);
        }
        
        /// <remarks/>
        public void GetServerDateAsync(object userState) {
            if ((this.GetServerDateOperationCompleted == null)) {
                this.GetServerDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerDateOperationCompleted);
            }
            this.InvokeAsync("GetServerDate", new object[0], this.GetServerDateOperationCompleted, userState);
        }
        
        private void OnGetServerDateOperationCompleted(object arg) {
            if ((this.GetServerDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerDateCompleted(this, new GetServerDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpresas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEmpresas() {
            object[] results = this.Invoke("GetEmpresas", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpresasAsync() {
            this.GetEmpresasAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpresasAsync(object userState) {
            if ((this.GetEmpresasOperationCompleted == null)) {
                this.GetEmpresasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpresasOperationCompleted);
            }
            this.InvokeAsync("GetEmpresas", new object[0], this.GetEmpresasOperationCompleted, userState);
        }
        
        private void OnGetEmpresasOperationCompleted(object arg) {
            if ((this.GetEmpresasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpresasCompleted(this, new GetEmpresasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GravaLogSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GravaLogSync(int COD_EMPREGADO, string TIPO_OPERACAO, string DSC_STATUS, string COD_REVENDA) {
            this.Invoke("GravaLogSync", new object[] {
                        COD_EMPREGADO,
                        TIPO_OPERACAO,
                        DSC_STATUS,
                        COD_REVENDA});
        }
        
        /// <remarks/>
        public void GravaLogSyncAsync(int COD_EMPREGADO, string TIPO_OPERACAO, string DSC_STATUS, string COD_REVENDA) {
            this.GravaLogSyncAsync(COD_EMPREGADO, TIPO_OPERACAO, DSC_STATUS, COD_REVENDA, null);
        }
        
        /// <remarks/>
        public void GravaLogSyncAsync(int COD_EMPREGADO, string TIPO_OPERACAO, string DSC_STATUS, string COD_REVENDA, object userState) {
            if ((this.GravaLogSyncOperationCompleted == null)) {
                this.GravaLogSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGravaLogSyncOperationCompleted);
            }
            this.InvokeAsync("GravaLogSync", new object[] {
                        COD_EMPREGADO,
                        TIPO_OPERACAO,
                        DSC_STATUS,
                        COD_REVENDA}, this.GravaLogSyncOperationCompleted, userState);
        }
        
        private void OnGravaLogSyncOperationCompleted(object arg) {
            if ((this.GravaLogSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GravaLogSyncCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsEmpregado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsEmpregado(int COD_EMPREGADO, string COD_REVENDA) {
            object[] results = this.Invoke("IsEmpregado", new object[] {
                        COD_EMPREGADO,
                        COD_REVENDA});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsEmpregadoAsync(int COD_EMPREGADO, string COD_REVENDA) {
            this.IsEmpregadoAsync(COD_EMPREGADO, COD_REVENDA, null);
        }
        
        /// <remarks/>
        public void IsEmpregadoAsync(int COD_EMPREGADO, string COD_REVENDA, object userState) {
            if ((this.IsEmpregadoOperationCompleted == null)) {
                this.IsEmpregadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsEmpregadoOperationCompleted);
            }
            this.InvokeAsync("IsEmpregado", new object[] {
                        COD_EMPREGADO,
                        COD_REVENDA}, this.IsEmpregadoOperationCompleted, userState);
        }
        
        private void OnIsEmpregadoOperationCompleted(object arg) {
            if ((this.IsEmpregadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsEmpregadoCompleted(this, new IsEmpregadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUpdateInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpdateInfo GetUpdateInfo(string name, string arch, int maj, int min, int bld) {
            object[] results = this.Invoke("GetUpdateInfo", new object[] {
                        name,
                        arch,
                        maj,
                        min,
                        bld});
            return ((UpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdateInfoAsync(string name, string arch, int maj, int min, int bld) {
            this.GetUpdateInfoAsync(name, arch, maj, min, bld, null);
        }
        
        /// <remarks/>
        public void GetUpdateInfoAsync(string name, string arch, int maj, int min, int bld, object userState) {
            if ((this.GetUpdateInfoOperationCompleted == null)) {
                this.GetUpdateInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdateInfoOperationCompleted);
            }
            this.InvokeAsync("GetUpdateInfo", new object[] {
                        name,
                        arch,
                        maj,
                        min,
                        bld}, this.GetUpdateInfoOperationCompleted, userState);
        }
        
        private void OnGetUpdateInfoOperationCompleted(object arg) {
            if ((this.GetUpdateInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdateInfoCompleted(this, new GetUpdateInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCabFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCabFiles() {
            object[] results = this.Invoke("GetCabFiles", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCabFilesAsync() {
            this.GetCabFilesAsync(null);
        }
        
        /// <remarks/>
        public void GetCabFilesAsync(object userState) {
            if ((this.GetCabFilesOperationCompleted == null)) {
                this.GetCabFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCabFilesOperationCompleted);
            }
            this.InvokeAsync("GetCabFiles", new object[0], this.GetCabFilesOperationCompleted, userState);
        }
        
        private void OnGetCabFilesOperationCompleted(object arg) {
            if ((this.GetCabFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCabFilesCompleted(this, new GetCabFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificaVersaoDLL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerificaVersaoDLL(ref string mensagem, string versaoCompativel, string versaoAplicativoAvanteSales) {
            object[] results = this.Invoke("VerificaVersaoDLL", new object[] {
                        mensagem,
                        versaoCompativel,
                        versaoAplicativoAvanteSales});
            mensagem = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificaVersaoDLLAsync(string mensagem, string versaoCompativel, string versaoAplicativoAvanteSales) {
            this.VerificaVersaoDLLAsync(mensagem, versaoCompativel, versaoAplicativoAvanteSales, null);
        }
        
        /// <remarks/>
        public void VerificaVersaoDLLAsync(string mensagem, string versaoCompativel, string versaoAplicativoAvanteSales, object userState) {
            if ((this.VerificaVersaoDLLOperationCompleted == null)) {
                this.VerificaVersaoDLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificaVersaoDLLOperationCompleted);
            }
            this.InvokeAsync("VerificaVersaoDLL", new object[] {
                        mensagem,
                        versaoCompativel,
                        versaoAplicativoAvanteSales}, this.VerificaVersaoDLLOperationCompleted, userState);
        }
        
        private void OnVerificaVersaoDLLOperationCompleted(object arg) {
            if ((this.VerificaVersaoDLLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificaVersaoDLLCompleted(this, new VerificaVersaoDLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargaImagem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CargaImagem(long espacoDisponivelAndroid, string codRevenda, string[] imagensExistentes) {
            object[] results = this.Invoke("CargaImagem", new object[] {
                        espacoDisponivelAndroid,
                        codRevenda,
                        imagensExistentes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargaImagemAsync(long espacoDisponivelAndroid, string codRevenda, string[] imagensExistentes) {
            this.CargaImagemAsync(espacoDisponivelAndroid, codRevenda, imagensExistentes, null);
        }
        
        /// <remarks/>
        public void CargaImagemAsync(long espacoDisponivelAndroid, string codRevenda, string[] imagensExistentes, object userState) {
            if ((this.CargaImagemOperationCompleted == null)) {
                this.CargaImagemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaImagemOperationCompleted);
            }
            this.InvokeAsync("CargaImagem", new object[] {
                        espacoDisponivelAndroid,
                        codRevenda,
                        imagensExistentes}, this.CargaImagemOperationCompleted, userState);
        }
        
        private void OnCargaImagemOperationCompleted(object arg) {
            if ((this.CargaImagemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaImagemCompleted(this, new CargaImagemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Carga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Carga(string[] dataParams) {
            object[] results = this.Invoke("Carga", new object[] {
                        dataParams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargaAsync(string[] dataParams) {
            this.CargaAsync(dataParams, null);
        }
        
        /// <remarks/>
        public void CargaAsync(string[] dataParams, object userState) {
            if ((this.CargaOperationCompleted == null)) {
                this.CargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaOperationCompleted);
            }
            this.InvokeAsync("Carga", new object[] {
                        dataParams}, this.CargaOperationCompleted, userState);
        }
        
        private void OnCargaOperationCompleted(object arg) {
            if ((this.CargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaCompleted(this, new CargaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargaParcial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CargaParcial(string[] dataParams) {
            object[] results = this.Invoke("CargaParcial", new object[] {
                        dataParams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargaParcialAsync(string[] dataParams) {
            this.CargaParcialAsync(dataParams, null);
        }
        
        /// <remarks/>
        public void CargaParcialAsync(string[] dataParams, object userState) {
            if ((this.CargaParcialOperationCompleted == null)) {
                this.CargaParcialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargaParcialOperationCompleted);
            }
            this.InvokeAsync("CargaParcial", new object[] {
                        dataParams}, this.CargaParcialOperationCompleted, userState);
        }
        
        private void OnCargaParcialOperationCompleted(object arg) {
            if ((this.CargaParcialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargaParcialCompleted(this, new CargaParcialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Descarga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Descarga(string[] dataParams) {
            this.Invoke("Descarga", new object[] {
                        dataParams});
        }
        
        /// <remarks/>
        public void DescargaAsync(string[] dataParams) {
            this.DescargaAsync(dataParams, null);
        }
        
        /// <remarks/>
        public void DescargaAsync(string[] dataParams, object userState) {
            if ((this.DescargaOperationCompleted == null)) {
                this.DescargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDescargaOperationCompleted);
            }
            this.InvokeAsync("Descarga", new object[] {
                        dataParams}, this.DescargaOperationCompleted, userState);
        }
        
        private void OnDescargaOperationCompleted(object arg) {
            if ((this.DescargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DescargaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateInfo {
        
        private string urlField;
        
        private bool isAvailableField;
        
        private string newVersionField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAvailable {
            get {
                return this.isAvailableField;
            }
            set {
                this.isAvailableField = value;
            }
        }
        
        /// <remarks/>
        public string newVersion {
            get {
                return this.newVersionField;
            }
            set {
                this.newVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetServerDateCompletedEventHandler(object sender, GetServerDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpresasCompletedEventHandler(object sender, GetEmpresasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpresasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpresasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GravaLogSyncCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsEmpregadoCompletedEventHandler(object sender, IsEmpregadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsEmpregadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsEmpregadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUpdateInfoCompletedEventHandler(object sender, GetUpdateInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdateInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdateInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCabFilesCompletedEventHandler(object sender, GetCabFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCabFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCabFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void VerificaVersaoDLLCompletedEventHandler(object sender, VerificaVersaoDLLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificaVersaoDLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificaVersaoDLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CargaImagemCompletedEventHandler(object sender, CargaImagemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaImagemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaImagemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CargaCompletedEventHandler(object sender, CargaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CargaParcialCompletedEventHandler(object sender, CargaParcialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargaParcialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargaParcialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DescargaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591